### ISSUE TITLE
paddle - paddledetection 训练入门

### ISSUE THREAD

**Issue by ooolky** [ooolky/NoteBook#10]
文档：

[快速上手PaddleDetection](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/docs/tutorials/GETTING_STARTED_cn.md)

任务列表：
- [x] [配置 paddledetection 环境](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/docs/tutorials/INSTALL_cn.md)
- [x] [准备数据](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/docs/tutorials/data/PrepareDetDataSet.md)
- [x] 修改配置文件
- [x] 训练
- [x] 评估
- [x] 预测

**Comment by ooolky** [comment]
[ 配置 paddledetection 环境](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/docs/tutorials/INSTALL_cn.md)

**Comment by ooolky** [comment]
> 配置 paddledetection 环境

运行`pip install -r requirements.txt`报错：`Failed building wheel for lap`
<details><summary>Details</summary>
<p>
Building wheel for lap (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Partial import of lap during the build process.
      Traceback (most recent call last):
        File "/tmp/pip-install-uiv8e0vd/lap_93ce3567c40046019a83362341af56d3/setup.py", line 127, in get_numpy_status
          import numpy
      ModuleNotFoundError: No module named 'numpy'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-uiv8e0vd/lap_93ce3567c40046019a83362341af56d3/setup.py", line 236, in <module>
          setup_package()
        File "/tmp/pip-install-uiv8e0vd/lap_93ce3567c40046019a83362341af56d3/setup.py", line 220, in setup_package
          raise ImportError('lap requires numpy, '
      ImportError: lap requires numpy, please "pip install numpy".
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lap
  Running setup.py clean for lap
Successfully built sklearn pycocotools
Failed to build lap
Installing collected packages: rarfile, pyclipper, lap, xmltodict, Werkzeug, tzdata, typeguard, threadpoolctl, terminaltables, pyparsing, pycryptodome, protobuf, numpy, kiwisolver, joblib, itsdangerous, fonttools, Cython, cycler, blinker, Babel, shapely, scipy, pandas, opencv-python, flask, contourpy, bce-python-sdk, scikit-learn, motmetrics, matplotlib, Flask-Babel, visualdl, sklearn, pycocotools
  Running setup.py install for lap ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for lap did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Partial import of lap during the build process.
      Traceback (most recent call last):
        File "/tmp/pip-install-uiv8e0vd/lap_93ce3567c40046019a83362341af56d3/setup.py", line 127, in get_numpy_status
          import numpy
      ModuleNotFoundError: No module named 'numpy'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-uiv8e0vd/lap_93ce3567c40046019a83362341af56d3/setup.py", line 236, in <module>
          setup_package()
        File "/tmp/pip-install-uiv8e0vd/lap_93ce3567c40046019a83362341af56d3/setup.py", line 220, in setup_package
          raise ImportError('lap requires numpy, '
      ImportError: lap requires numpy, please "pip install numpy".
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lap

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
</p>
</details>

**Comment by ooolky** [comment]
> > 配置 paddledetection 环境
> 
> 运行`pip install -r requirements.txt`报错：`Failed building wheel for lap`

✔解决
- 运行`conda install -c conda-forge lap`
- [参考](https://blog.csdn.net/qq_52908337/article/details/123282347)

**Comment by ooolky** [comment]
> 配置 paddledetection 环境

运行`pip install -r requirements.txt`报错：`requires protobuf<=3.20.0,>=3.1.0, but you have protobuf 4.23.3 which is incompatible`

**Comment by ooolky** [comment]
> > 配置 paddledetection 环境
> 
> 运行`pip install -r requirements.txt`报错：`requires protobuf<=3.20.0,>=3.1.0, but you have protobuf 4.23.3 which is incompatible`

✔解决
运行`pip install protobuf==3.20.0`

**Comment by ooolky** [comment]
> 训练

问题❓
运行：
`export CUDA_VISIBLE_DEVICES=0,2`
`python -m paddle.distributed.launch --gpus 0,2 tools/train.py -c configs/yolov3/yolov3_mobilenet_v1_roadsign.yml`
报错：
`0   paddle::pybind::ThrowExceptionToPython(std::__exception_ptr::exception_ptr)`
<details><summary>Details</summary>
<p>

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::pybind::ThrowExceptionToPython(std::__exception_ptr::exception_ptr)

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1687888438 (unix time) try "date -d @1687888438" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3eb0006e652) received by PID 452178 (TID 0x7fc04f3a8500) from PID 452178 ***]

LAUNCH INFO 2023-06-28 01:54:01,003 Exit code -15
[2023-06-28 01:54:01,003] [    INFO] controller.py:141 - Exit code -15

</p>
</details>

**Comment by ooolky** [comment]
> > 训练
> 
> 问题❓ 运行： `export CUDA_VISIBLE_DEVICES=0,2` `python -m paddle.distributed.launch --gpus 0,2 tools/train.py -c configs/yolov3/yolov3_mobilenet_v1_roadsign.yml` 报错： `0 paddle::pybind::ThrowExceptionToPython(std::__exception_ptr::exception_ptr)`

解决✔
原因：`nvidia-smi`显示的显卡编号和`CUDA_VISIBLE_DEVICES`对不上，指定了显存不足的显卡引发报错，要分别对每张单卡测试来确定正确的编号。
运行：
`export CUDA_VISIBLE_DEVICES=0,1`
`python -m paddle.distributed.launch --gpus 0,1 tools/train.py -c configs/yolov3/yolov3_mobilenet_v1_roadsign.yml`
