### ISSUE TITLE
conda - 报错：No module named '_distutils_hack'

### ISSUE THREAD

**Issue by ooolky** [ooolky/NoteBook#13]
背景：
linux
conda虚拟环境

运行命令：
`conda`

报错：
Error processing line 1 of /home/nerc-likaiyuan/env/anaconda3/lib/python3.10/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/home/nerc-likaiyuan/env/anaconda3/lib/python3.10/site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored

**Comment by ooolky** [comment]
- 打开error对应的`distutils-precedence.pth`，将`import os;`后面加上一个enter换行
- [参考](https://blog.csdn.net/qq_45040216/article/details/125119982)
